//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_SiteInformation
    {
        public int Id { get; set; }
        public int StateId { get; set; }
        public string SiteCode { get; set; }
        public string SiteCodeExposedInfants { get; set; }
        public string SiteCodePediatric { get; set; }
        public string SiteCodePMTCT { get; set; }
        public string SiteCodeVCT { get; set; }
        public string SiteNameInformal { get; set; }
        public string SiteNameOfficial { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
