//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_MessagingPatientComplaint
    {
        public long Id { get; set; }
        public string MessageId { get; set; }
        public System.DateTime SentDate { get; set; }
        public string SentByNumber { get; set; }
        public string SentByPatient { get; set; }
        public string MessageText { get; set; }
        public int CurrentCaseStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
