//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_PatientRegistrationLog
    {
        public long Id { get; set; }
        public System.DateTime DateLogged { get; set; }
        public string PepId { get; set; }
        public int ClientId { get; set; }
        public bool IsBioDataCaptured { get; set; }
        public bool IsNfcDataCaptured { get; set; }
        public int ReasonForVisit { get; set; }
        public bool IsDeleted { get; set; }
    }
}
