//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_SiteInformation
    {
        public int Id { get; set; }
        public string SiteName { get; set; }
        public string SiteAddress { get; set; }
        public int SiteStateId { get; set; }
        public System.DateTime DateConfigured { get; set; }
        public bool IsDeleted { get; set; }
    }
}
