//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_ClientLog
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int CurrentUserId { get; set; }
        public System.DateTime DateLog { get; set; }
        public string LocationLat { get; set; }
        public string LocationLong { get; set; }
        public string ChipData { get; set; }
        public bool IsDeleted { get; set; }
    }
}
