//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration_StaffInformation
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string PasswordData { get; set; }
        public string PasswordSalt { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public int SiteId { get; set; }
        public int AuthenticationState { get; set; }
        public bool IsDeleted { get; set; }
        public int RoleId { get; set; }
    }
}
