//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__MigrationLog
    {
        public System.Guid migration_id { get; set; }
        public string script_checksum { get; set; }
        public string script_filename { get; set; }
        public System.DateTime complete_dt { get; set; }
        public string applied_by { get; set; }
        public byte deployed { get; set; }
        public string version { get; set; }
        public string package_version { get; set; }
        public string release_version { get; set; }
        public int sequence_no { get; set; }
    }
}
