//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integration_SystemGatewayLicence
    {
        public int Id { get; set; }
        public System.DateTime LoadPeriod { get; set; }
        public long LastLoadAmount { get; set; }
        public long CurrentLoadAmount { get; set; }
        public long CurrentBalance { get; set; }
        public string LoadKey { get; set; }
        public System.DateTime LastDeductionPeriod { get; set; }
        public bool IsCurrentStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
