//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integration_SystemProviderDeliveryLogs
    {
        public long Id { get; set; }
        public string MessageId { get; set; }
        public Nullable<System.DateTime> OperationDate { get; set; }
        public int OperationStatus { get; set; }
        public bool IsFinalStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
