//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Integration_SystemAppointmentDataItem
    {
        public long Id { get; set; }
        public System.DateTime DateLogged { get; set; }
        public string AppointmentOffice { get; set; }
        public string PepId { get; set; }
        public string GeneratedMessage { get; set; }
        public bool OperationStatus { get; set; }
        public bool IsDeleted { get; set; }
        public string AppointmentData { get; set; }
        public System.DateTime AppointmentDate { get; set; }
    }
}
