//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_PatientBiometricDataPopulationRegister
    {
        public int Id { get; set; }
        public string HtsId { get; set; }
        public string FingerPrimary { get; set; }
        public string FingerSecondary { get; set; }
        public string FingerDataHash { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public bool IsValid { get; set; }
        public bool IsDeleted { get; set; }
        public string FingerPrimaryPosition { get; set; }
        public string FingerSecondaryPosition { get; set; }
    }
}
