//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_PatientBiometricIntegrityCase
    {
        public int Id { get; set; }
        public System.DateTime DateGenerated { get; set; }
        public string PivotPepId { get; set; }
        public string CaseName { get; set; }
        public string CaseDescription { get; set; }
        public int CaseStatus { get; set; }
        public bool IsDeleted { get; set; }
    }
}
