//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_PatientInformation
    {
        public int Id { get; set; }
        public string PepId { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Othername { get; set; }
        public string Sex { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<decimal> PatientPhysicalDataHeight { get; set; }
        public Nullable<decimal> PatientPhysicalDataWeight { get; set; }
        public int StateOfOrigin { get; set; }
        public int SiteId { get; set; }
        public int HospitalId { get; set; }
        public int BioDataId { get; set; }
        public byte[] PassportData { get; set; }
        public bool IsDeleted { get; set; }
    }
}
