//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administration_ClientLog> Administration_ClientLog { get; set; }
        public virtual DbSet<Administration_ClientMap> Administration_ClientMap { get; set; }
        public virtual DbSet<Administration_ClientRegistry> Administration_ClientRegistry { get; set; }
        public virtual DbSet<Administration_PatientRegistrationLog> Administration_PatientRegistrationLog { get; set; }
        public virtual DbSet<Administration_SiteInformation> Administration_SiteInformation { get; set; }
        public virtual DbSet<Administration_StaffInformation> Administration_StaffInformation { get; set; }
        public virtual DbSet<Patient_PatientBiometricData> Patient_PatientBiometricData { get; set; }
        public virtual DbSet<Patient_PatientInformation> Patient_PatientInformation { get; set; }
        public virtual DbSet<Patient_PatientNearFieldCommunicationData> Patient_PatientNearFieldCommunicationData { get; set; }
        public virtual DbSet<Patient_PatientTransferHistory> Patient_PatientTransferHistory { get; set; }
        public virtual DbSet<System_LocalGovermentArea> System_LocalGovermentArea { get; set; }
        public virtual DbSet<System_State> System_State { get; set; }
        public virtual DbSet<System_Update> System_Update { get; set; }
    
        public virtual ObjectResult<Sp_Administration_GetInActiveUsers_Result> Sp_Administration_GetInActiveUsers(Nullable<int> inactiveBar)
        {
            var inactiveBarParameter = inactiveBar.HasValue ?
                new ObjectParameter("inactiveBar", inactiveBar) :
                new ObjectParameter("inactiveBar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Administration_GetInActiveUsers_Result>("Sp_Administration_GetInActiveUsers", inactiveBarParameter);
        }
    
        public virtual ObjectResult<string> Sp_Administration_GetPatientCompliance()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Sp_Administration_GetPatientCompliance");
        }
    
        public virtual ObjectResult<Sp_Administration_GetAgeDistro_Result> Sp_Administration_GetAgeDistro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Administration_GetAgeDistro_Result>("Sp_Administration_GetAgeDistro");
        }
    }
}
