//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_PatientBiometricDataSecondary
    {
        public int Id { get; set; }
        public string PepId { get; set; }
        public int DataModel { get; set; }
        public string DataSet { get; set; }
        public string BioDataExtract { get; set; }
        public int BioDataScore { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public System.DateTime DateRegistered { get; set; }
        public bool IsDeleted { get; set; }
    }
}
