//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_ClientPulse
    {
        public long Id { get; set; }
        public System.DateTime CheckInPeriod { get; set; }
        public string ClientId { get; set; }
        public long UserId { get; set; }
        public string AppVersion { get; set; }
        public bool IsDeleted { get; set; }
    }
}
