//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_NotificationLog
    {
        public int Id { get; set; }
        public int NotificationId { get; set; }
        public System.DateTime DateLastSent { get; set; }
        public int Interval { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsLatest { get; set; }
    }
}
