//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_DataIntegrityActionLog
    {
        public long Id { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int ActionUser { get; set; }
        public int ActionType { get; set; }
        public string DataBefore { get; set; }
        public string DataAfter { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsReversed { get; set; }
        public int ActionReversedUser { get; set; }
        public System.DateTime ActionReversedDate { get; set; }
    }
}
