//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.Client
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LocalPDAEntities : DbContext
    {
        public LocalPDAEntities()
            : base("name=LocalPDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Local_StaffInformation> Local_StaffInformation { get; set; }
        public virtual DbSet<System_BioDataStore> System_BioDataStore { get; set; }
        public virtual DbSet<System_EndPointLog> System_EndPointLog { get; set; }
        public virtual DbSet<System_ErrorLog> System_ErrorLog { get; set; }
        public virtual DbSet<System_LocalGovermentArea> System_LocalGovermentArea { get; set; }
        public virtual DbSet<System_Setting> System_Setting { get; set; }
        public virtual DbSet<System_SiteData> System_SiteData { get; set; }
        public virtual DbSet<System_State> System_State { get; set; }
        public virtual DbSet<System_UpdateLog> System_UpdateLog { get; set; }
    
        public virtual int Sp_System_CleanUp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_System_CleanUp");
        }
    }
}
