

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "PatientDataAdministration.DemoClient\App.config"
//     Connection String Name: "DemoDbContext"
//     Connection String:      "Data Source=C:\Users\Arigbede\Source\Repos\patient-data-administration\PatientDataAdministration.DemoClient\\DemoDb.sdf"
// ------------------------------------------------------------------------------------------------
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PatientDataAdministration.DemoClient
{
    using System.Linq;

    #region Unit of work

    public interface IDemoDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<BioRegLog> BioRegLogs { get; set; } // BioRegLog
        System.Data.Entity.DbSet<PatientData> PatientDatas { get; set; } // PatientData
        System.Data.Entity.DbSet<SiteData> SiteDatas { get; set; } // SiteData

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class DemoDbContext : System.Data.Entity.DbContext, IDemoDbContext
    {
        public System.Data.Entity.DbSet<BioRegLog> BioRegLogs { get; set; } // BioRegLog
        public System.Data.Entity.DbSet<PatientData> PatientDatas { get; set; } // PatientData
        public System.Data.Entity.DbSet<SiteData> SiteDatas { get; set; } // SiteData

        static DemoDbContext()
        {
            System.Data.Entity.Database.SetInitializer<DemoDbContext>(null);
        }

        public DemoDbContext()
            : base("Name=DemoDbContext")
        {
        }

        public DemoDbContext(string connectionString)
            : base(connectionString)
        {
        }

        public DemoDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public DemoDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public DemoDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new BioRegLogConfiguration());
            modelBuilder.Configurations.Add(new PatientDataConfiguration());
            modelBuilder.Configurations.Add(new SiteDataConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new BioRegLogConfiguration(schema));
            modelBuilder.Configurations.Add(new PatientDataConfiguration(schema));
            modelBuilder.Configurations.Add(new SiteDataConfiguration(schema));
            return modelBuilder;
        }
    }
    #endregion

    #region Fake Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class FakeDemoDbContext : IDemoDbContext
    {
        public System.Data.Entity.DbSet<BioRegLog> BioRegLogs { get; set; }
        public System.Data.Entity.DbSet<PatientData> PatientDatas { get; set; }
        public System.Data.Entity.DbSet<SiteData> SiteDatas { get; set; }

        public FakeDemoDbContext()
        {
            BioRegLogs = new FakeDbSet<BioRegLog>("Id");
            PatientDatas = new FakeDbSet<PatientData>("Id");
            SiteDatas = new FakeDbSet<SiteData>("Id");
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        public System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
        public System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
        public System.Data.Entity.Database _database;
        public System.Data.Entity.Database Database { get { return _database; } }
        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
        {
            throw new System.NotImplementedException();
        }
        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet Set(System.Type entityType)
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            throw new System.NotImplementedException();
        }

    }

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
    {
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;

        public FakeDbSet()
        {
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new System.ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
        }

        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
            return items;
        }

        public override TEntity Add(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
            return items;
        }

        public override TEntity Remove(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Remove(item);
            return item;
        }

        public override TEntity Attach(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override TEntity Create()
        {
            return System.Activator.CreateInstance<TEntity>();
        }

        public override TDerivedEntity Create<TDerivedEntity>()
        {
            return System.Activator.CreateInstance<TDerivedEntity>();
        }

        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
        {
            get { return _data; }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
    {
        private readonly IQueryProvider _inner;

        public FakeDbAsyncQueryProvider(IQueryProvider inner)
        {
            _inner = inner;
        }

        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TEntity>(expression);
        }

        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TElement>(expression);
        }

        public object Execute(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute(expression);
        }

        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute<TResult>(expression);
        }

        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute(expression));
        }

        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
            : base(enumerable)
        { }

        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
            : base(expression)
        { }

        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
        {
            return GetAsyncEnumerator();
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<T>(this); }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
    {
        private readonly System.Collections.Generic.IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public void Dispose()
        {
            _inner.Dispose();
        }

        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
        {
            get { return Current; }
        }
    }

    #endregion

    #region POCO classes

    // BioRegLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BioRegLog
    {
        public int Id { get; set; } // Id (Primary key)
        public System.DateTime? DateRegistered { get; set; } // DateRegistered
        public string PepId { get; set; } // PepId (length: 100)
        public bool? IsDeleted { get; set; } // IsDeleted

        public BioRegLog()
        {
            DateRegistered = System.DateTime.Now;
        }
    }

    // PatientData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class PatientData
    {
        public int Id { get; set; } // Id (Primary key)
        public string PepId { get; set; } // PepId (length: 100)
        public string SiteName { get; set; } // SiteName (length: 100)
        public string Surname { get; set; } // Surname (length: 100)
        public string Othernames { get; set; } // Othernames (length: 100)
        public string Sex { get; set; } // Sex (length: 100)
        public string MaritalStatus { get; set; } // MaritalStatus (length: 100)
        public string PhoneHumber { get; set; } // PhoneHumber (length: 100)
        public string Email { get; set; } // Email (length: 100)
        public string HouseAddress { get; set; } // HouseAddress (length: 100)
        public System.DateTime DateOfBirth { get; set; } // DateOfBirth
        public string StateOfOrigin { get; set; } // StateOfOrigin (length: 50)
        public decimal? VitalsHeight { get; set; } // VitalsHeight
        public decimal? VitalsWeight { get; set; } // VitalsWeight
        public string FacilityNumber { get; set; } // FacilityNumber (length: 100)
        public string ClientNumber { get; set; } // ClientNumber (length: 100)
        public string HospitalNumber { get; set; } // HospitalNumber (length: 100)
        public string PassportImage { get; set; } // PassportImage (length: 536870911)
        public string BioDataFingerPrimary { get; set; } // BioDataFingerPrimary (length: 536870911)
        public string BioDataFingerSecondary { get; set; } // BioDataFingerSecondary (length: 536870911)
        public string CardDataUid { get; set; } // CardDataUid (length: 536870911)
        public string CardDataChip { get; set; } // CardDataChip (length: 536870911)
        public bool IsDeleted { get; set; } // IsDeleted
        public string TagData { get; set; } // TagData (length: 100)
    }

    // SiteData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SiteData
    {
        public int Id { get; set; } // Id (Primary key)
        public string SiteName { get; set; } // SiteName (length: 100)
        public string SiteCode { get; set; } // SiteCode (length: 100)
        public string SiteCodeExposedInfants { get; set; } // SiteCodeExposedInfants (length: 100)
        public string SiteCodePediatric { get; set; } // SiteCodePediatric (length: 100)
        public string SiteCodePmtct { get; set; } // SiteCodePMTCT (length: 100)
        public string SiteCodeVct { get; set; } // SiteCodeVCT (length: 100)
        public string SiteNameInformal { get; set; } // SiteNameInformal (length: 100)
        public bool IsDeleted { get; set; } // IsDeleted

        public SiteData()
        {
            IsDeleted = false;
        }
    }

    #endregion

    #region POCO Configuration

    // BioRegLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class BioRegLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BioRegLog>
    {
        public BioRegLogConfiguration()
            : this("")
        {
        }

        public BioRegLogConfiguration(string schema)
        {
            ToTable("BioRegLog");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DateRegistered).HasColumnName(@"DateRegistered").HasColumnType("datetime").IsOptional();
            Property(x => x.PepId).HasColumnName(@"PepId").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsOptional();
        }
    }

    // PatientData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class PatientDataConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PatientData>
    {
        public PatientDataConfiguration()
            : this("")
        {
        }

        public PatientDataConfiguration(string schema)
        {
            ToTable("PatientData");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.PepId).HasColumnName(@"PepId").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.SiteName).HasColumnName(@"SiteName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Surname).HasColumnName(@"Surname").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Othernames).HasColumnName(@"Othernames").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Sex).HasColumnName(@"Sex").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.MaritalStatus).HasColumnName(@"MaritalStatus").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.PhoneHumber).HasColumnName(@"PhoneHumber").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.HouseAddress).HasColumnName(@"HouseAddress").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType("datetime").IsRequired();
            Property(x => x.StateOfOrigin).HasColumnName(@"StateOfOrigin").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.VitalsHeight).HasColumnName(@"VitalsHeight").HasColumnType("numeric").IsOptional().HasPrecision(18,0);
            Property(x => x.VitalsWeight).HasColumnName(@"VitalsWeight").HasColumnType("numeric").IsOptional().HasPrecision(18,0);
            Property(x => x.FacilityNumber).HasColumnName(@"FacilityNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.ClientNumber).HasColumnName(@"ClientNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.HospitalNumber).HasColumnName(@"HospitalNumber").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.PassportImage).HasColumnName(@"PassportImage").HasColumnType("ntext").IsOptional().IsMaxLength();
            Property(x => x.BioDataFingerPrimary).HasColumnName(@"BioDataFingerPrimary").HasColumnType("ntext").IsOptional().IsMaxLength();
            Property(x => x.BioDataFingerSecondary).HasColumnName(@"BioDataFingerSecondary").HasColumnType("ntext").IsOptional().IsMaxLength();
            Property(x => x.CardDataUid).HasColumnName(@"CardDataUid").HasColumnType("ntext").IsOptional().IsMaxLength();
            Property(x => x.CardDataChip).HasColumnName(@"CardDataChip").HasColumnType("ntext").IsOptional().IsMaxLength();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
            Property(x => x.TagData).HasColumnName(@"TagData").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
        }
    }

    // SiteData
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public class SiteDataConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SiteData>
    {
        public SiteDataConfiguration()
            : this("")
        {
        }

        public SiteDataConfiguration(string schema)
        {
            ToTable("SiteData");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SiteName).HasColumnName(@"SiteName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.SiteCode).HasColumnName(@"SiteCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.SiteCodeExposedInfants).HasColumnName(@"SiteCodeExposedInfants").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.SiteCodePediatric).HasColumnName(@"SiteCodePediatric").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.SiteCodePmtct).HasColumnName(@"SiteCodePMTCT").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.SiteCodeVct).HasColumnName(@"SiteCodeVCT").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.SiteNameInformal).HasColumnName(@"SiteNameInformal").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();
        }
    }

    #endregion

}
// </auto-generated>

