//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.DemoClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientData
    {
        public int Id { get; set; }
        public string PepId { get; set; }
        public int SiteId { get; set; }
        public string Surname { get; set; }
        public string Othernames { get; set; }
        public string Sex { get; set; }
        public string PhoneHumber { get; set; }
        public string Email { get; set; }
        public string HouseAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string StateOfOrigin { get; set; }
        public Nullable<decimal> VitalsHeight { get; set; }
        public Nullable<decimal> VitalsWeight { get; set; }
        public string FacilityNumber { get; set; }
        public string ClientNumber { get; set; }
        public string HospitalNumber { get; set; }
        public string BioDataFingerPrimary { get; set; }
        public string BioDataFingerSecondary { get; set; }
        public string CardDataUid { get; set; }
        public string CardDataChip { get; set; }
        public bool IsDeleted { get; set; }
    }
}
