//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientDataAdministration.DemoClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteData
    {
        public int Id { get; set; }
        public string SiteName { get; set; }
        public int IsDeleted { get; set; }
    }
}
